(function(global){
'use strict';
const ENDPOINT=global.CENTRAL_CLOUD_ENDPOINT||'https://script.google.com/macros/s/AKfycbyxmDMgk-h2lTuf_6BvUngMLu-yMDvfenHNshQ3aa0V3lDPzh5kosUfiqm90IugmepPpw/exec';
let v10Enabled=global.CENTRAL_V10_ENABLED===true;
const TOKEN_KEY='pmpb-central-token-v1',P3_TOKEN_KEY='pmpb-p3-token-v1',QUEUE_KEY='pmpb-central-sync-queue-v1',DEVICE_KEY='pmpb-device-id-v1';
function uid(p='id'){try{return p+'-'+crypto.randomUUID()}catch(_){return p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2)}}
function formatMatricula(v){const d=String(v||'').replace(/\D/g,'').slice(0,7);return d.length<=3?d:d.length<=6?d.slice(0,3)+'.'+d.slice(3):d.slice(0,3)+'.'+d.slice(3,6)+'-'+d.slice(6)}
function getDeviceId(){try{let d=localStorage.getItem(DEVICE_KEY)||'';if(!d){d=uid('dev');localStorage.setItem(DEVICE_KEY,d)}return d}catch(_){return uid('dev')}}
function getToken(kind='central'){try{return localStorage.getItem(kind==='p3'?P3_TOKEN_KEY:TOKEN_KEY)||''}catch(_){return ''}}
function setToken(v,kind='central'){try{const k=kind==='p3'?P3_TOKEN_KEY:TOKEN_KEY;if(v)localStorage.setItem(k,v);else localStorage.removeItem(k)}catch(_){}}
function askToken(kind='central',message,force=false){let t=force?'':getToken(kind);if(t)return t;t=prompt(message||(kind==='p3'?'Informe a Chave P3:':'Informe a chave operacional da Central:'))||'';t=t.trim();if(t)setToken(t,kind);return t}
const P3_ACTIONS=new Set(['p3-query','p3-analysis','p3-config','motomecanizacao-list','checklist-list','motomecanizacao-update','cadastro-upsert','p3-config-set','rco-upsert','rco-retification-open']);
function tokenKindForAction(action){return P3_ACTIONS.has(String(action||''))?'p3':'central'}
function isAuthError(err){return err?.code==='AUTH_INVALID'||/(chave|credencial)[^\n]{0,80}inválid/i.test(String(err?.message||err||''))}
function authError(action,message,token,kindOverride){const e=new Error(message||'Chave inválida.');if(/(chave|credencial)[^\n]{0,80}inválid/i.test(e.message)){const kind=kindOverride||tokenKindForAction(action);e.code='AUTH_INVALID';e.tokenKind=kind;if(kind==='central'||kind==='p3'){const saved=getToken(kind);if(!token||!saved||String(saved)===String(token))setToken('',kind)}}return e}
function clearToken(kind='central'){setToken('',kind)}
function unitParams(u={}){let b=String(u.batalhao||u.batalhaoSigla||'BPTran');b=b.toUpperCase()==='BPRV'?'BPRv':'BPTran';let n=Number(u.companhiaNumero)||Number(String(u.companhia||'').match(/\d+/)?.[0])||1;n=Math.min(5,Math.max(1,n));return {batalhao:b,companhiaNumero:String(n),companhia:n+'ª '+(b==='BPRv'?'CPRv':'CPTran')}}
function qs(obj){return Object.entries(obj||{}).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(String(v))).join('&')}
function jsonp(action,params={},opts={}){return new Promise((resolve,reject)=>{
  const callback='__central_cb_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script');
  let done=false,timer;
  function cleanup(){clearTimeout(timer);try{delete global[callback]}catch(_){global[callback]=undefined}script.remove()}
  function finish(err,data){if(done)return;done=true;cleanup();err?reject(err):resolve(data)}
  global[callback]=function(data){
    if(data&&data.ok===false)finish(authError(action,data.message||'Consulta rejeitada.',params.token));
    else finish(null,data||{ok:false,message:'Resposta vazia da Central.'});
  };
  script.async=true;
  script.onerror=()=>finish(new Error('Falha de comunicação com a Central.'));
  script.src=ENDPOINT+'?'+qs({...params,action,callback,_:Date.now()});
  (document.head||document.documentElement).appendChild(script);
  timer=setTimeout(()=>finish(new Error('Tempo esgotado ao consultar a Central.')),opts.timeout||20000);
})}
function submitForm(action,payload,token,opts={}){return new Promise((resolve,reject)=>{const requestId=uid('post'),name='central_post_'+Date.now()+'_'+Math.random().toString(36).slice(2);let win=null,iframe=null,target=name;if(opts.popup!==false){win=window.open('about:blank',name,'width=620,height=540');if(!win){reject(new Error('O navegador bloqueou a janela de confirmação. Permita pop-ups e tente novamente.'));return}}else{iframe=document.createElement('iframe');iframe.name=name;iframe.style.display='none';document.body.appendChild(iframe)}const form=document.createElement('form');form.method='POST';form.action=ENDPOINT;form.target=target;form.style.display='none';for(const [k,v] of Object.entries({action,token,requestId,payload:JSON.stringify(payload||{})})){const i=document.createElement('input');i.type='hidden';i.name=k;i.value=v;form.appendChild(i)}let timer;const onMsg=e=>{const d=e.data;if(!d||d.source!=='central-p3-v10'||d.action!==action||String(d.requestId||'')!==requestId)return;cleanup();d.ok?resolve(d):reject(authError(action,d.message||'Operação rejeitada.',token,opts.tokenKind))};function cleanup(){clearTimeout(timer);global.removeEventListener('message',onMsg);form.remove();if(iframe)setTimeout(()=>iframe.remove(),400)}global.addEventListener('message',onMsg);document.body.appendChild(form);form.submit();timer=setTimeout(()=>{cleanup();reject(new Error('Tempo esgotado ao comunicar com a Central.'))},opts.timeout||20000)})}
function readQueue(){try{const x=JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return []}}
function writeQueue(q){try{localStorage.setItem(QUEUE_KEY,JSON.stringify(q.slice(-100)))}catch(_){}}
function enqueue(action,payload,unit,token){const q=readQueue();q.push({id:uid('sync'),action,payload,unit,token:token||'',tokenKind:tokenKindForAction(action),createdAt:new Date().toISOString(),tries:0});writeQueue(q);return q.length}
async function postOrQueue(action,payload,{token,unit,popup=false}={}){const kind=tokenKindForAction(action),t=token||getToken(kind);if(!navigator.onLine){enqueue(action,payload,unit,t);return {ok:true,queued:true,message:'Sem conexão: dados preservados para sincronização.'}}try{return await submitForm(action,payload,t,{popup})}catch(err){if(isAuthError(err))throw err;enqueue(action,payload,unit,t);return {ok:true,queued:true,message:'Envio pendente: '+err.message}}}
async function retryQueue(){if(!navigator.onLine)return {sent:0,pending:readQueue().length,authRequired:0};const q=readQueue(),left=[];let sent=0,authRequired=0;for(const item of q){const kind=item.tokenKind||tokenKindForAction(item.action),t=item.token||getToken(kind);try{await submitForm(item.action,item.payload,t,{popup:false,timeout:8000});sent++}catch(err){item.tries=(item.tries||0)+1;if(isAuthError(err)){item.token='';item.tokenKind=kind;authRequired++}left.push(item)}}writeQueue(left);return {sent,pending:left.length,authRequired}}
function queueCount(){return readQueue().length}
async function compressImage(file,{maxSide=1600,quality=.78,type='image/jpeg'}={}){if(!file)return null;const img=await new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u});let w=img.naturalWidth,h=img.naturalHeight,s=Math.min(1,maxSide/Math.max(w,h));w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);const dataUrl=canvas.toDataURL(type,quality);return {dataUrl,mimeType:type,largura:w,altura:h,tamanhoBytes:Math.round((dataUrl.length-dataUrl.indexOf(',')-1)*.75)}}
async function searchCadastro(tipo,q,u,token){const isMilitar=String(tipo||'').toLowerCase().indexOf('militar')===0,up=isMilitar?{}:unitParams(u);let t=token||getToken('central')||askToken('central','Informe a chave operacional da Central para consultar o Cadastro Mestre:');if(!t)throw new Error('Consulta cancelada: chave operacional não informada.');try{return await jsonp('cadastros',{...up,tipo,q,token:t})}catch(err){if(!isAuthError(err))throw err;t=askToken('central','A chave informada é inválida. Digite novamente a chave operacional da Central:',true);if(!t)throw new Error('Consulta cancelada: chave operacional não informada.');return await jsonp('cadastros',{...up,tipo,q,token:t})}}
function ensureProgressUi(){
 if(document.getElementById('centralProgressOverlay'))return;
 const st=document.createElement('style');st.id='centralProgressStyle';st.textContent='#centralProgressOverlay{position:fixed;inset:0;z-index:30000;background:rgba(15,23,42,.36);display:none;align-items:center;justify-content:center;padding:18px;pointer-events:auto}#centralProgressOverlay.open{display:flex}#centralProgressCard{width:min(460px,100%);background:#fff;border-radius:16px;padding:18px;box-shadow:0 24px 70px rgba(0,0,0,.32);color:#17375e;font:700 14px Arial}#centralProgressText{margin-bottom:10px}#centralProgressTrack{height:8px;border-radius:999px;background:#e6edf3;overflow:hidden}#centralProgressBar{height:100%;width:35%;border-radius:999px;background:#315f93;animation:central-progress 1.15s ease-in-out infinite alternate}@keyframes central-progress{from{transform:translateX(-20%)}to{transform:translateX(220%)}}#centralSyncBadge{position:fixed;right:10px;bottom:10px;z-index:1200;padding:4px 8px;border-radius:12px;background:rgba(255,255,255,.48);color:#496176;font:700 10px Arial;opacity:.55;pointer-events:none;box-shadow:none;border:0;backdrop-filter:blur(2px)}body.signature-open #centralSyncBadge,.auto-signature-modal.open~#centralSyncBadge{opacity:.18}';
 document.head.appendChild(st);
 const o=document.createElement('div');o.id='centralProgressOverlay';o.className='no-print';o.innerHTML='<div id="centralProgressCard" role="status" aria-live="polite"><div id="centralProgressText">Processando…</div><div id="centralProgressTrack"><div id="centralProgressBar"></div></div></div>';document.body.appendChild(o);
}
function showProgress(message='Processando…'){ensureProgressUi();const o=document.getElementById('centralProgressOverlay'),t=document.getElementById('centralProgressText');if(t)t.textContent=message;o?.classList.add('open')}
function updateProgress(message){const t=document.getElementById('centralProgressText');if(t&&message)t.textContent=message}
function hideProgress(){document.getElementById('centralProgressOverlay')?.classList.remove('open')}
function installStatusBadge(){if(document.getElementById('centralSyncBadge'))return;ensureProgressUi();const b=document.createElement('div');b.id='centralSyncBadge';b.className='no-print';function refresh(){const n=queueCount();b.textContent=n?'☁ '+n+' envio(s) pendente(s)':'☁ Sincronizado';b.style.color=n?'#8a5a00':'#176b3a';b.style.opacity=n?'.82':'.5'}document.body.appendChild(b);refresh();global.addEventListener('online',()=>setTimeout(async()=>{await retryQueue();refresh()},800));setInterval(refresh,2500)} 
async function probe(){if(v10Enabled)return true;try{const r=await jsonp('version',{}, {timeout:10000});v10Enabled=!!(r&&r.ok&&String(r.version||'').startsWith('10'));if(v10Enabled)global.dispatchEvent(new CustomEvent('central-v10-ready',{detail:r}));return v10Enabled}catch(_){return false}}
global.CentralCloud={ENDPOINT,get V10_ENABLED(){return v10Enabled},isEnabled:()=>v10Enabled,probe,uid,formatMatricula,getDeviceId,getToken,setToken,clearToken,askToken,isAuthError,tokenKindForAction,unitParams,jsonp,submitForm,postOrQueue,retryQueue,queueCount,compressImage,searchCadastro,installStatusBadge,showProgress,updateProgress,hideProgress};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installStatusBadge();setTimeout(probe,150)});else{installStatusBadge();setTimeout(probe,150)}
})(window);
