(function(global){
'use strict';
const ENDPOINT=global.CENTRAL_CLOUD_ENDPOINT||'https://script.google.com/macros/s/AKfycbyxmDMgk-h2lTuf_6BvUngMLu-yMDvfenHNshQ3aa0V3lDPzh5kosUfiqm90IugmepPpw/exec';
let v10Enabled=global.CENTRAL_V10_ENABLED===true;
const TOKEN_KEY='pmpb-central-token-v1',P3_TOKEN_KEY='pmpb-p3-token-v1',QUEUE_KEY='pmpb-central-sync-queue-v1';
function uid(p='id'){try{return p+'-'+crypto.randomUUID()}catch(_){return p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2)}}
function formatMatricula(v){const d=String(v||'').replace(/\D/g,'').slice(0,7);return d.length<=3?d:d.length<=6?d.slice(0,3)+'.'+d.slice(3):d.slice(0,3)+'.'+d.slice(3,6)+'-'+d.slice(6)}
function getToken(kind='central'){try{return localStorage.getItem(kind==='p3'?P3_TOKEN_KEY:TOKEN_KEY)||''}catch(_){return ''}}
function setToken(v,kind='central'){try{const k=kind==='p3'?P3_TOKEN_KEY:TOKEN_KEY;if(v)localStorage.setItem(k,v);else localStorage.removeItem(k)}catch(_){}}
function askToken(kind='central',message){let t=getToken(kind);if(t)return t;t=prompt(message||(kind==='p3'?'Informe a Chave P3:':'Informe a chave operacional da Central:'))||'';t=t.trim();if(t)setToken(t,kind);return t}
function unitParams(u={}){let b=String(u.batalhao||u.batalhaoSigla||'BPTran');b=b.toUpperCase()==='BPRV'?'BPRv':'BPTran';let n=Number(u.companhiaNumero)||Number(String(u.companhia||'').match(/\d+/)?.[0])||1;n=Math.min(5,Math.max(1,n));return {batalhao:b,companhiaNumero:String(n),companhia:n+'ª '+(b==='BPRv'?'CPRv':'CPTran')}}
function qs(obj){return Object.entries(obj||{}).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(String(v))).join('&')}
function jsonp(action,params={},opts={}){return new Promise((resolve,reject)=>{const cb='__central_cb_'+Date.now()+'_'+Math.random().toString(36).slice(2);let done=false;const timer=setTimeout(()=>finish(new Error('Tempo esgotado ao consultar a Central.')),opts.timeout||20000);function finish(err,data){if(done)return;done=true;clearTimeout(timer);try{delete global[cb]}catch(_){};script.remove();err?reject(err):resolve(data)}global[cb]=data=>{if(data&&data.ok===false)finish(new Error(data.message||'Consulta rejeitada.'));else finish(null,data)};const script=document.createElement('script');script.onerror=()=>finish(new Error('Falha de comunicação com a Central.'));script.src=ENDPOINT+'?'+qs({...params,action,callback:cb,_:Date.now()});document.head.appendChild(script)})}
function submitForm(action,payload,token,opts={}){return new Promise((resolve,reject)=>{const name='central_post_'+Date.now()+'_'+Math.random().toString(36).slice(2);let win=null,iframe=null,target=name;if(opts.popup!==false){win=window.open('about:blank',name,'width=620,height=540');if(!win){reject(new Error('O navegador bloqueou a janela de confirmação. Permita pop-ups e tente novamente.'));return}}else{iframe=document.createElement('iframe');iframe.name=name;iframe.style.display='none';document.body.appendChild(iframe)}const form=document.createElement('form');form.method='POST';form.action=ENDPOINT;form.target=target;form.style.display='none';for(const [k,v] of Object.entries({action,token,payload:JSON.stringify(payload||{})})){const i=document.createElement('input');i.type='hidden';i.name=k;i.value=v;form.appendChild(i)}let timer;const onMsg=e=>{const d=e.data;if(!d||d.source!=='central-p3-v10'||d.action!==action)return;cleanup();d.ok?resolve(d):reject(new Error(d.message||'Operação rejeitada.'))};function cleanup(){clearTimeout(timer);global.removeEventListener('message',onMsg);form.remove();if(iframe)setTimeout(()=>iframe.remove(),2000)}global.addEventListener('message',onMsg);document.body.appendChild(form);form.submit();timer=setTimeout(()=>{cleanup();if(opts.popup===false)resolve({ok:true,queued:true,message:'Envio realizado; confirme a sincronização posteriormente.'});else resolve({ok:true,pending:true,message:'Envio aberto para confirmação.'})},opts.timeout||15000)})}
function readQueue(){try{const x=JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return []}}
function writeQueue(q){try{localStorage.setItem(QUEUE_KEY,JSON.stringify(q.slice(-100)))}catch(_){}}
function enqueue(action,payload,unit,token){const q=readQueue();q.push({id:uid('sync'),action,payload,unit,token:token||'',createdAt:new Date().toISOString(),tries:0});writeQueue(q);return q.length}
async function postOrQueue(action,payload,{token,unit,popup=false}={}){const t=token||getToken('central');if(!navigator.onLine){enqueue(action,payload,unit,t);return {ok:true,queued:true,message:'Sem conexão: dados preservados para sincronização.'}}try{return await submitForm(action,payload,t,{popup})}catch(err){enqueue(action,payload,unit,t);return {ok:true,queued:true,message:'Envio pendente: '+err.message}}}
async function retryQueue(){if(!navigator.onLine)return {sent:0,pending:readQueue().length};const q=readQueue(),left=[];let sent=0;for(const item of q){try{await submitForm(item.action,item.payload,item.token||getToken('central'),{popup:false,timeout:8000});sent++}catch(_){item.tries=(item.tries||0)+1;left.push(item)}}writeQueue(left);return {sent,pending:left.length}}
function queueCount(){return readQueue().length}
async function compressImage(file,{maxSide=1600,quality=.78,type='image/jpeg'}={}){if(!file)return null;const img=await new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u});let w=img.naturalWidth,h=img.naturalHeight,s=Math.min(1,maxSide/Math.max(w,h));w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);const dataUrl=canvas.toDataURL(type,quality);return {dataUrl,mimeType:type,largura:w,altura:h,tamanhoBytes:Math.round((dataUrl.length-dataUrl.indexOf(',')-1)*.75)}}
async function searchCadastro(tipo,q,u,token){const isMilitar=String(tipo||'').toLowerCase().indexOf('militar')===0;const up=isMilitar?{}:unitParams(u);return jsonp('cadastros',{...up,tipo,q,token:token||getToken('central')})}
function installStatusBadge(){if(document.getElementById('centralSyncBadge'))return;const b=document.createElement('button');b.type='button';b.id='centralSyncBadge';b.className='no-print';Object.assign(b.style,{position:'fixed',right:'10px',bottom:'10px',zIndex:9998,border:'1px solid #b7c5d1',borderRadius:'18px',padding:'7px 11px',background:'#fff',color:'#24425f',font:'700 11px Arial',boxShadow:'0 4px 16px #0002'});function refresh(){const n=queueCount();b.textContent=n?'☁ '+n+' envio(s) pendente(s)':'☁ Sincronizado';b.style.color=n?'#8a5a00':'#176b3a'}b.onclick=async()=>{b.disabled=true;const r=await retryQueue();b.disabled=false;refresh();if(r.sent)alert(r.sent+' envio(s) sincronizado(s).')};document.body.appendChild(b);refresh();global.addEventListener('online',()=>setTimeout(async()=>{await retryQueue();refresh()},800))} 
async function probe(){if(v10Enabled)return true;try{const r=await jsonp('version',{}, {timeout:10000});v10Enabled=!!(r&&r.ok&&String(r.version||'').startsWith('10'));if(v10Enabled)global.dispatchEvent(new CustomEvent('central-v10-ready',{detail:r}));return v10Enabled}catch(_){return false}}
global.CentralCloud={ENDPOINT,get V10_ENABLED(){return v10Enabled},isEnabled:()=>v10Enabled,probe,uid,formatMatricula,getToken,setToken,askToken,unitParams,jsonp,submitForm,postOrQueue,retryQueue,queueCount,compressImage,searchCadastro,installStatusBadge};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installStatusBadge();setTimeout(probe,150)});else{installStatusBadge();setTimeout(probe,150)}
})(window);
